# Q3 Using Scikit-Learn

In [1]:
import numpy as np
import pandas as pd
import time
import gc
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [2]:
# Change to your GA Tech ID
ga_id = 'rliang37'
# Requires a print() statement do not modify below print statement
print(ga_id)

rliang37


# Q3.1 Data Import and Cleansing Setup

In [3]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set. We've started this for you. 
# XXX

# -------------------------------
# ADD CODE HERE
# data = pd.read_csv('xxx')
# -------------------------------
data = pd.read_csv('pulsar_stars.csv')

# XXX
# TODO: Separate out the x_data and y_data. We've started this for you.
# XXX

# -------------------------------
# ADD CODE HERE
# x_data = data.loc[]
# y_data = data.loc[]
# -------------------------------
x_data = data.loc[:, data.columns != "y"]
y_data = data.loc[:, "y"]

In [4]:
# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' 
# set to 614.
# 

# -------------------------------
# ADD CODE HERE
# -------------------------------
random_state = 614
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state= random_state, shuffle = True)


# Q3.2 Linear Regression 

In [5]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
# 
# -------------------------------
lr = LinearRegression()
lr.fit(x_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
res_train_lr = lr.predict(x_train)
res_train_lr = res_train_lr.round()
score_train_lr = accuracy_score(res_train_lr, y_train)
print("The accuracy of the linear regression is %f" % (score_train_lr*100))

The accuracy of the linear regression is 97.142401


In [7]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
res_test_lr = lr.predict(x_test)
res_test_lr = res_test_lr.round()
score_test_lr = accuracy_score(res_test_lr, y_test)
print("The accuracy of the linear regression is %f" % (score_test_lr*100))

The accuracy of the linear regression is 96.890130


# Q3.3 Random Forest Classifier

In [8]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# Set 'random_state' to 614
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------
rfc =RandomForestClassifier(random_state=random_state)
rfc.fit(x_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=614,
                       verbose=0, warm_start=False)

In [9]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
res_train_rfc = rfc.predict(x_train) 
score_train_rfc = accuracy_score(res_train_rfc, y_train) 
print("The accuracy of the Random Forest Classifier is %f" % (score_train_rfc*100))

The accuracy of the Random Forest Classifier is 99.680715


In [10]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
res_test_rfc = rfc.predict(x_test)
score_test_rfc = accuracy_score(res_test_rfc, y_test)
print("The accuracy of the Random Forest Classifier is %f" % (score_test_rfc*100))

The accuracy of the Random Forest Classifier is 97.672253


## Q3.3.1 Feature Importance

In [11]:
# XXX
# TODO: Determine the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
rfc_feature_importance = rfc.feature_importances_

print(rfc_feature_importance)

[0.36631348 0.05096543 0.25857456 0.11768744 0.05862141 0.03806286
 0.05627799 0.05349682]


In [12]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
sorted_feature_num = np.argsort(rfc_feature_importance)[::-1][:len(rfc_feature_importance)]
print(sorted_feature_num)

[0 2 3 4 6 7 1 5]


## Q3.3.2 Hyper-parameter Tuning

In [13]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# 'n_estimators': [4, 16, 256]
# 'max_depth': [2, 8, 16]
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------
hyper_parameters = {'n_estimators':[4, 16,256], 'max_depth':[2, 8, 16]}
rfc_tunning = GridSearchCV(rfc, hyper_parameters, cv=10)
rfc_tunning.fit(x_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=10, n_jobs=None,
                                              oob_score=False, random_state=614,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'ma

In [14]:
# XXX
# TODO: Get the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
best_parameters = rfc_tunning.best_params_
print(best_parameters)


{'max_depth': 16, 'n_estimators': 256}


In [15]:
# XXX
# TODO: Get the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
best_score = rfc_tunning.best_score_

print(best_score)

0.9798850574712644


# Q3.4 Support Vector Machine

## Q3.4.1 Pre-process

In [16]:
# XXX
# TODO: Pre-process the data to standardize it, otherwise the grid search will take much longer.
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------
n_x_train = normalize(x_train)
n_x_test = normalize(x_test)

## Q3.4.2 Classification

In [17]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------

svm = SVC(gamma='auto')
svm.fit(n_x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [18]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------

res_train_svm = svm.predict(n_x_train)
score_train_svm = accuracy_score(res_train_svm, y_train)

print("The accuracy of the SVM is %f" % (score_train_svm*100))

The accuracy of the SVM is 96.942848


In [19]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------

res_test_svm = svm.predict(n_x_test)
score_test_svm = accuracy_score(res_test_svm, y_test)

print("The accuracy of the SVM is %f" % (score_test_svm*100))

The accuracy of the SVM is 96.629423


## Q3.4.3 Hyper-parameter Tuning

In [24]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# 'kernel':('linear', 'rbf') 
# 'C':[0.01, 0.1, 1.0]
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------
params_svc = {'C': [0.01,0.1, 1.0], 'kernel': ['linear', 'rbf']}
tuned_svc = SVC(gamma='auto')
svm2 = GridSearchCV(tuned_svc, params_svc, cv = 10)
svm2.fit(n_x_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.01, 0.1, 1.0], 'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [25]:
# XXX
# TODO: Get the best score, using .best_score_.
# Note: Set n_jobs=-1 and return_train_score=True
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
print("best score: %f" % svm2.best_score_)

best score: 0.972302


In [29]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and standardization. 
# XXX

# -------------------------------
# ADD CODE HERE
# -------------------------------

res_train_svm2 = svm2.predict(n_x_train)
score_train_svm2 = accuracy_score(res_train_svm2, y_train)

res_test_svm2 = svm2.predict(n_x_test)
score_test_svm2 = accuracy_score(res_test_svm2, y_test)

# print(score_train_svm2)
# print(score_test_svm2)

In [30]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
print(score_train_svm2)

0.9724616858237548


In [31]:
# XXX
# TODO: Test its accuracy (on the test set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
print(score_test_svm2)

0.9702048417132216


## Q3.4.4 Cross Validation Results 

In [32]:
# XXX
# TODO: Get the rank test score for all hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------

rank_test_score = svm2.cv_results_['rank_test_score']
print(rank_test_score)

[5 6 3 4 1 2]


In [33]:
# XXX
# TODO: Get the mean testing score for all of hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX
# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
mean_test_score = svm2.cv_results_['mean_test_score']
print(mean_test_score)

[0.9548212  0.90844508 0.96607599 0.9589719  0.97230204 0.96886973]


# Q3.5 PCA

In [ ]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# NOTE: Use the full x data set for this section 'x_data'

# -------------------------------
# ADD CODE HERE
# You should see an output here of PCA(copy=True....)
# -------------------------------
pca = PCA(n_component=8, svd_solver='full')
pca.fit_

In [ ]:
# XXX
# TODO: Get percentage of variance explained by each of the selected components
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------

In [ ]:
# XXX
# TODO: Get the singular values corresponding to each of the selected components.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------